config/routes.rb
Rails.application.routes.draw do
  resources :user_site_sessions
  devise_for :users
  resources :users
  resources :sites

  mount Localtower::Engine, at: 'localtower' if Rails.env.development?

  get 'site/index'

  root to: 'site#index'
  get  'report'   => 'site#report'
  post 'generate' => 'site#generate'
end

app/models/site.rb
require 'soft_deletion'
# this is the site model. this stores Go Karting track information
class Site < ActiveRecord::Base
  has_soft_deletion default_scope: true

  before_soft_delete :validate_deletability # soft_delete stops if this returns false
  after_soft_delete :send_deletion_emails

  has_many :user_site_sessions, dependent: :destroy
end

app/controllers/site_controller.rb
# controller
class SiteController < ApplicationController
  # site controller. handles report generation mostly.
  require 'date'
  
    def find_last_day_of_month(my_date)
      if my_date.instance_of? String
        @end_of_the_month = (Date.parse(my_date).next_month - 1).to_s
      elsif _date.instance_of? Date
        @end_of_the_month = my_date.next_month.strftime('%Y-%m-01') - 1
      end
      @end_of_the_month
    end

    def index; end

    def report
      @sites = Site.all
    end

    def generate
      @form_vals = params[:user_site_session]
      sanitize_inputs
      @service = UserSiteSessionReporterService.new(@form_vals)
      @res = @service.build_query
      render 'generate', locals: { msg: @msg }
    end

    def sanitize_inputs
      validate_params
      handle_deletion_of_keys
    end

    def handle_deletion_of_keys
      @decimal = "/(^(\d+)(\.)?(\d+)?)|(^(\d+)?(\.)(\d+))/"
      examine_lap_time_from(@form_vals) if @form_vals['lap_time_from'].present?
      examine_lap_time_to(@form_vals) if @form_vals['lap_time_to'].present?
    end

    def examine_lap_time_from
      @form_vals.delete('lap_time_from') unless @form_vals['lap_time_from'] =~ @decimal
      @form_vals.delete('lap_time_to') unless @form_vals['lap_time_from'] =~ @decimal
    end

    def examine_lap_time_to
      @form_vals.delete('lap_time_from') unless form_vals['lap_time_to'] =~ @decimal
      @form_vals.delete('lap_time_to') unless form_vals['lap_time_to'] =~ @decimal
    end

    def validate_params
      regex = '^(?:199[0-9]|20[0-9][0-9])-(?:0[1-9]|1[0-2])-(?:[0-2][0-9]|3[0-1])$'
      if @form_vals['site_id'].blank?
        @msg = 'Please select a venue.'
      elsif @form_vals['date_from'].match(regex).nil?
        @msg = 'Date From is not valid. Please enter in YYYY-MM-DD format.'
      elsif @form_vals['date_to'].blank?
        to = find_last_day_of_month(@form_vals['date_from'])
        @form_vals['date_to'] = to
      elsif @form_vals['date_to'].match(regex).nil?
        @msg = 'Date To is not valid. Please enter in YYYY-MM-DD format.'
      end
    end
end

app/controllers/sites_controller.rb
# controller
class SitesController < ApplicationController
  # not to confuse yourself with @SiteController.
  # this handles the actions for Venue CRUD actions.
  load_and_authorize_resource
  before_action :set_site, only: %i(show edit update destroy)

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, alert: exception.message
  end

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @leaderboard = UserSiteSession.select('
      user_site_sessions.*, users.name as "user_name"
    ').joins(:user).where(site_id: params[:id]).all_quickest
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit; end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:name, :location)
    end
end

app/helpers/site_helper.rb
# module
module SiteHelper
end

app/helpers/sites_helper.rb
# module
module SitesHelper
end

app/views/sites/_form.html.erb
<%= simple_form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="card">
  <h2 class="card-header bg-primary"><% if @site.new_record? %> New Venue <% else %> Edit Venue <% end %></h2>
  <div class="card-body">

  <div class="row">
    <div class='col-lg-4'>
      <%= f.label :name %>
    </div>
    <div class="col-lg-8">
      <%= f.input :name , label: false %>
    </div>
  </div>

  <div class="row">
    <div class='col-lg-4'>
      <%= f.label :location %>
    </div>
    <div class="col-lg-8">
      <%= f.input :location , label: false %>
    </div>
  </div>
  

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

  </div>
</div>

app/views/sites/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <h2 class="card-header bg-primary">All Venues</h2>
  <div class="card-body">

<table class="table table-striped table-bordered data-table">
  <thead>
    <tr class="warning">
      <th>Name</th>
      <% if can? :manage, 'Site' %>
      <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><a href="/sites/<%=site.id%>"><%= site.name %></a></td>
        <% if can? :manage, 'Site' %>
        <td><%= link_to 'Show', site %></td>
        <td><%= link_to 'Edit', edit_site_path(site) %></td>
        <td><%= link_to 'Remove', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

  </div>
</div>

<br>

<% if can? :manage, 'Site' %>
  <%= link_to 'New Venue', new_site_path , class: 'btn btn-success' %>
<% end %>

app/views/sites/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <h2 class="card-header bg-primary"><%= @site.name %></h2>
  <div class="card-body">

<p>
  <strong>Location: </strong>
  <%= @site.location %>
</p>

<% if current_user %>
	<% if can? :edit, Site %>
	<%= link_to 'Edit', edit_site_path(@site) %> |
	<% end %>
	<%= link_to 'Back', sites_path %>
<% end %>

<hr />
<h2>All Lap Times For This Venue</h2> 
<p>
	<table class="table table-striped table-bordered data-table">
		<thead>
			<tr class="warning">
				<th>Position</th>
				<th>Name</th>
				<th>Time</th>
			</tr>
		</thead>
		<tbody>
			<% i =1 %>
			<% lastScore = 0
			   lastPos = 0 
			%>
			<% @leaderboard.each do |participant| %>
			<tr>
				<% myPosition = i %>
				<% 
				if(lastScore > 0 && participant.lap_time == lastScore)
					myPosition = lastPos
				end
				lastScore = participant.lap_time
				lastPos = myPosition
				%>
				<td><%=myPosition%></td>
				<td><%=participant.user_name%></td>
				<td><%=participant.lap_time%> seconds</td>
			</tr>
			<%i +=1 %>
			<% end %>
		</tbody>

	</table>
</p>
</div></div>