config/routes.rb
Rails.application.routes.draw do
  resources :user_site_sessions
  devise_for :users
  resources :users
  resources :sites

  mount Localtower::Engine, at: 'localtower' if Rails.env.development?

  get 'site/index'

  root to: 'site#index'
  get  'report'   => 'site#report'
  post 'generate' => 'site#generate'
end

app/models/user_site_session.rb
# model
class UserSiteSession < ActiveRecord::Base
  enum weather: %i(sunny rainy overcast)
  belongs_to :user
  belongs_to :site
  validate :session_date_cannot_be_in_the_future

  def session_date_cannot_be_in_the_future
    errors.add(:session_date, "can't be in the future") if session_date? && session_date > Time.Zone.today
  end

  scope :me, -> { where(user: User.current_user).order(lap_time: :ASC) }

  scope :all_quickest, -> { order(lap_time: :ASC) }

  def self.fetch_lap_times
    select(
      'user_site_sessions.*, users.name as user_name, sites.name as venue_name'
    ).joins(:user, :site)
  end
end

app/controllers/user_site_sessions_controller.rb
# controller
class UserSiteSessionsController < ApplicationController
  # handles actions for CRUD actions for Lap Time records.
  before_action :set_user_site_session, only: %i(show edit update destroy)
  before_action :check_logged_in

  # GET /user_site_sessions
  # GET /user_site_sessions.json
  def index
    load_query
  end

  # GET /user_site_sessions/1
  # GET /user_site_sessions/1.json
  def show; end

  # GET /user_site_sessions/new
  def new
    @user_site_session = UserSiteSession.new
    @user = if can? :manage, 'User'
              User.all
            else
              current_user
            end
  end

  # GET /user_site_sessions/1/edit
  def edit; end

  # POST /user_site_sessions
  # POST /user_site_sessions.json
  def create
    before_create
    respond_to do |format|
      if @user_site_session.save
        format.html { redirect_to @user_site_session, notice: 'User site session was successfully created.' }
        format.json { render :show, status: :created, location: @user_site_session }
      else
        format.html { render :new }
        format.json { render json: @user_site_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_site_sessions/1
  # PATCH/PUT /user_site_sessions/1.json
  def update
    respond_to do |format|
      if @user_site_session.update(user_site_session_params)
        format.html { redirect_to @user_site_session, notice: 'User site session was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_site_session }
      else
        format.html { render :edit }
        format.json { render json: @user_site_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_site_sessions/1
  # DELETE /user_site_sessions/1.json
  def destroy
    @user_site_session.destroy
    respond_to do |format|
      format.html { redirect_to user_site_sessions_url, notice: 'User site session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user_site_session
    if current_user.user?
      @user_site_session = UserSiteSession.fetch_lap_times.find(params[:id])
      redirect_to '/user_site_sessions' if @user_site_session.user_id != current_user.id
    end
    @user_site_session = UserSiteSession.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_site_session_params
    params.require(:user_site_session).permit(:lap_time, :weather, :session_date, :site_id, :user_id)
  end

  def check_logged_in
    redirect_to '/' unless current_user
  end

  def before_create
    @user_site_session = UserSiteSession.new(user_site_session_params)
    @user_site_session.user_id = current_user.id if current_user && current_user.user?
  end

  def load_query
    if current_user.admin?
      @user_site_sessions = UserSiteSession.fetch_lap_times.all_quickest if params.key?('showAll')
      @user_site_sessions = UserSiteSession.fetch_lap_times.me unless params.key?('showAll')
    elsif current_user.user?
      @user_site_sessions = UserSiteSession.fetch_lap_times.me
    end
  end
end

app/helpers/user_site_sessions_helper.rb
# module
module UserSiteSessionsHelper
end

app/views/user_site_sessions/_form.html.erb
<%= simple_form_for(@user_site_session) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="card">
  <h2 class="card-header bg-primary"><% if @user_site_session.new_record? %> New Lap Time <% else %> Edit Lap Time <% end %></h2>
  <div class="card-body">
    <% if current_user && current_user.admin? %>
    <div class="row">
      <div class='col-lg-4'>
        <%= f.label :user_id %>
      </div>
      <div class="col-lg-8">
            <%= f.input :user_id, collection: User.all, prompt: "Select User", selected: @user_site_session.user_id, label: false %>
      </div>
    </div>
    <% end %>

    <div class="row">
      <div class='col-lg-4'>
        <%= f.label :site_id, label: 'Venue' %>
      </div>
      <div class="col-lg-8">
            <%= f.input :site_id, collection: Site.all, prompt: "Select Venue", selected: @user_site_session.site_id, label: false %>
      </div>
    </div>

    <div class="row">
      <div class='col-lg-4'>
        <%= f.label :session_date, label: 'Session Date' %>
      </div>
      <div class="col-lg-8">
            <%= f.input :session_date, label: false %>
      </div>
    </div>

    <div class="row">
      <div class='col-lg-4'>
        <%= f.label :weather %>
      </div>
      <div class="col-lg-8">
            <%= f.input :weather, label: false %>
      </div>
    </div>

    <div class="row">
      <div class='col-lg-4'>
        <%= f.label :lap_time %>
      </div>
      <div class="col-lg-8">
            <%= f.input :lap_time, label: false %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.button :submit , @user_site_session.new_record? ? 'Create Lap Time' : 'Update Lap Time' %>
    </div>

  </div>
</div>
<% end %>

app/views/user_site_sessions/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @user_site_session %> |
<%= link_to 'Back', user_site_sessions_path %>

app/views/user_site_sessions/index.html.erb
<p id="notice"><%= notice %></p>




<div class="card">
  <h2 class="card-header bg-primary"><% if params.key?('showAll') == false %>
My Lap Times
<% else %>
<% if current_user.admin? %>
All Lap Times
<% else %>
My Lap Times
<% end %>
<% end %></h2>
  <div class="card-body">

<table class="table table-striped table-bordered data-tables">
  <thead>
    <tr class="warning">
      <th>Lap Times</th>
      <th>User</th>
      <th>Venue</th>
      <th>Weather</th>
      <% if can? :limitedmanage, UserSiteSession %>
      <% i = 2 %>
      <% i += 1 if can? :delete, UserSiteSession %>
      <th colspan="<%=i%>"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @user_site_sessions.each do |user_site_session| %>
      <tr>
        <td><%= user_site_session.lap_time %></td>
        <td><%= user_site_session.user_name %></td>
        <td><%= user_site_session.venue_name %></td>
        <td><%= user_site_session.weather.humanize %></td>
        <% if can? :limitedmanage, UserSiteSession %>
        <td><%= link_to 'Show', user_site_session %></td>
        <% end %>
        <% if can? :limitedmanage, UserSiteSession %>
        <td><%= link_to 'Edit', edit_user_site_session_path(user_site_session) %></td>
        <% end %>
        <% if can? :delete, UserSiteSession %>
        <td><%= link_to 'Remove', user_site_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, UserSiteSession %>
<%= link_to 'New Lap Time', new_user_site_session_path, class: 'btn btn-success' %>
<% end %>

<% if current_user.admin? %>
  <% if params.key?('showAll') == false %>
    <a href="/user_site_sessions?showAll" class="btn btn-info">Show All Lap Times</a>
  <% else %>
    <a href="/user_site_sessions" class="btn btn-info">Show My Lap Times</a>
  <% end %>
<% end %>
</div>
</div>

app/views/user_site_sessions/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', user_site_sessions_path %>

app/views/user_site_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lap Time:</strong>
  <%= @user_site_session.lap_time %>
</p>

<p>
  <strong>Weather:</strong>
  <%= @user_site_session.weather.humanize %>
</p>

<p>
  <strong>Session date:</strong>
  <%= @user_site_session.session_date %>
</p>

<%= link_to 'Edit', edit_user_site_session_path(@user_site_session) %> |
<%= link_to 'Back', user_site_sessions_path %>